// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GooseDBVersion string
	Items          string
}{
	GooseDBVersion: "goose_db_version",
	Items:          "items",
}
